### PR TITLE
Update Translation for Chinese Traditional and Simplified

### PR DESCRIPTION
**Pull request by TragicLifeHu**
I tried Crowdin but  after opening the project files, nothing showed : (
Please help to fix that, so I could contribute to the translation easily
And as the XML I got there (Crowdin -> Export XML) and here (GitHub XML file) is not even, perhaps some sync job is needed

### CODE REVIEW

**Comment by kidonng** [comment]
Indeed, SAI's Crowdin project is not working. Could you please add this change to your PR? `冲 -> 从`

https://github.com/Aefyr/SAI/blob/55505d231b1390e824d1cc0c8f4fa35fd4677105/app/src/main/res/values-zh-rCN/strings.xml#L287

**Comment by TragicLifeHu** [comment]
Added, thanks for feedback
I also wonder when could the changes to be applied lol

**Comment by kidonng** [comment]
Keep it on please 😉

**Comment by TragicLifeHu** [comment]
Well, this project seems to be suspended, keeping pr do no work. Maybe I should create my own branch…

**Comment by singhalrishi27** [comment]
> Well, this project seems to be suspended, keeping pr do no work. Maybe I should create my own branch…

Yeah also please update the target sdk

**Pull request closed without merging**
