### PR TITLE
Dependencies and last AndroidX

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Group dependencies
- tooltips 1.0.10 -> 1.0.11
- fabric gradle 1.31.0 -> 1.31.2

### 2nd commit
- Migrate leftover support to AndroidX

### 3rd commit
- Move from deprecated firebase core to used dependencies

### CODE REVIEW

**Comment by Aefyr** [comment]
What's the point of splitting `firebase-core` into `firebase-analytics` and `firebase-common`?

**Comment by TacoTheDank** [comment]
@Aefyr https://firebase.google.com/support/release-notes/android#latest_sdk_versions in blue

**Comment by Aefyr** [comment]
> @Aefyr https://firebase.google.com/support/release-notes/android#latest_sdk_versions in blue

Oh, ok. But I haven't found a mention of `firebase-common`.

**Comment by TacoTheDank** [comment]
@Aefyr `firebase-common` is the dependency that contains `FirebaseApp`. Why it's not mentioned idk.

**Comment by TacoTheDank** [comment]
I googled it and found a thing https://github.com/firebase/firebase-android-sdk/tree/master/firebase-common

**Comment by Aefyr** [comment]
I've checked it without `firebase-common` and FirebaseApp is still exposed. Also `firebase-analytics` includes `firebase-common`. It may be supposed to be an internal dependency.
Anyway, I'm merging this, but I'll remove `firebase-common` just to be safe. Thanks for contributing.

**Comment by TacoTheDank** [comment]
Ok.

**Pull request merged**
